name: TinkLink
targets:
  TinkLink:
    type: framework
    platform: [iOS, macOS]
    info:
      path: Sources/TinkLink/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLink"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      MACOSX_DEPLOYMENT_TARGET: 10.13
      MARKETING_VERSION: 1.7.1
      CURRENT_PROJECT_VERSION: 4
    scheme:
      testTargets:
        - name: TinkLinkTests_${platform}
    sources:
      - Sources/TinkLink
    dependencies:
      - package: TinkCore
  TinkLinkTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkTests"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      MACOSX_DEPLOYMENT_TARGET: 10.13
    sources:
      - Tests/TinkLinkTests
    dependencies:
      - target: TinkLink_${platform}
      - package: TinkCore
  TinkLinkUI:
    type: framework
    platform: [iOS]
    info:
      path: Sources/TinkLinkUI/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUI"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      MARKETING_VERSION: 1.7.1
      CURRENT_PROJECT_VERSION: 4
    scheme:
      testTargets:
        - name: TinkLinkUITests_${platform}
    sources:
      - Sources/TinkLinkUI
    dependencies:
      - target: TinkLink_${platform}
      - package: TinkCore
      - package: Down
  TinkLinkUITests:
    type: bundle.unit-test
    platform: [iOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUITests"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
    sources:
      - Tests/TinkLinkUITests
    dependencies:
      - target: TinkLinkUI_${platform}
      - package: TinkCore
      - package: Down
  TinkLinkUIUITests:
    type: bundle.ui-testing
    platform: [iOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUIUITests"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      TEST_TARGET_NAME: "TinkLinkUIUITestsHost_iOS"
    sources:
      - Tests/TinkLinkUIUITests
    dependencies:
      - target: TinkLinkUIUITestsHost_${platform}
      - package: TinkLink
      - package: TinkLinkUI
  TinkLinkUIUITestsHost:
    type: application
    platform: [iOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUIUITestsHost"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
    sources:
      - Sources/TinkLinkUIUITestsHost
    scheme:
      testTargets:
        - name: TinkLinkUIUITests_${platform}
      environmentVariables:
        TINK_LINK_UI_TESTS_HOST_CLIENT_ID: $TINK_LINK_UI_TESTER_CLIENT_ID
    dependencies:
      - package: TinkLink
      - package: TinkLinkUI
  TinkLinkUIDevelopment:
    type: application
    platform: [iOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUIDevelopment"
        IPHONEOS_DEPLOYMENT_TARGET: 11.0
      configs:
        debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    sources:
      - Samples/TinkLinkExample/TinkLinkExample
    scheme:
      testTargets:
        - name: TinkLinkUIUITests_${platform}
      environmentVariables:
        TINK_LINK_EXAMPLE_CLIENT_ID: $TINK_CLIENT_ID
    dependencies:
      - target: TinkLinkUI_${platform}
packages:
  TinkLink:
    path: ./
  TinkLinkUI:
    path: ./
  TinkCore:
    url: https://github.com/tink-ab/tink-core-ios
    exactVersion: 1.7.0
  Down:
    url: https://github.com/johnxnguyen/Down
    exactVersion: 0.11.0
