platform :ios, "11.0"
use_frameworks!

target "TinkLinkUIExample" do

	pod "TinkCore", :path => "../../../tink-core-ios"
    pod "TinkLink", :path => "../../"
    pod "TinkLinkUI", :path => "../../"

end
