platform :ios, "11.0"
use_frameworks!

target "TinkLinkUIExample" do

    pod "TinkCore", :git => "https://github.com/tink-ab/tink-core-ios-private"
    pod "TinkLink", :path => "../../"
    pod "TinkLinkUI", :path => "../../"

end
