platform :ios, "11.0"
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target "TinkLinkTester" do

    pod "TinkCore", :git => "https://github.com/tink-ab/tink-core-ios-private"
    pod "TinkLink", :path => "../", :testspecs => ['TinkLinkTests']
    pod "TinkLinkUI", :path => "../", :testspecs => ['TinkLinkUITests']

end
