platform :ios, "11.0"
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target "TinkLinkTester" do

    pod "TinkCore", :path => "../../tink-core-ios"
    pod "TinkLink", :path => "../"
    pod "TinkLinkUI", :path => "../"

end
